# Generated by Django 5.0.6 on 2024-07-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_productmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
