# Generated by Django 5.0.6 on 2024-07-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productmodel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='requested', max_length=50),
        ),
    ]
